module Notifications
  AllTypes = [
    ReplyOnFollowedComment,
    ReplyOnFollowedDiscussionPost,
    CommentOnFollowedContent,
    MeetingAttended,
    CommentInMeeting,
    CommentOnOwnedContent,
    ReplyOnComment,
    CommentOnDiscussionPost,
    MeetingUpdated,
    NewGroupDiscussion,
    NewGroupMeeting,
    NewGroupPost,
    NewLocation,
    NewLocationPost,
    NewMeeting,
    NewRoomCall,
    NewRoomDemand,
    NewRoomOffer,
    NewToolOffer,
    NewToolDemand,
    NewWallComment,
    NewCoopDemand,
  ]
end
